# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universidad',
            options={'verbose_name': 'Universidad', 'verbose_name_plural': 'Universidades'},
        ),
        migrations.AddField(
            model_name='universidad',
            name='tipo',
            field=models.CharField(default='oooooooooooooooooo', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
