# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unsearch', '0002_auto_20160527_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrera',
            old_name='tipo',
            new_name='grado',
        ),
    ]
