# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsearch', '0003_auto_20160527_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
