# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unsearch', '0007_busqueda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busqueda',
            name='count',
        ),
    ]
