# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsearch', '0009_busqueda_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busqueda',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
