# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsearch', '0010_auto_20160703_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='busqueda',
            name='num_resultados',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
